name: Test
on: [push, pull_request]
jobs:
  test:
    name: pytest
    runs-on: windows-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: install deps
        run: pip install -r requirements.txt
      - name: pytest
        run: pytest
